### ISSUE TITLE
Investigating the possibilities to retrieve username of liked items

### ISSUE THREAD

**Issue by jjui** [JonMasterson/WordPress-Post-Like-System#12]
Wonderful code, thank you. 
Tho I'd like to retrieve all users that is liking the current item. 
Any pointers? I would be delighted.

**Comment by jjui** [comment]
So, to retrieve names of the ones liking: 
```
$get_who_is_liking = get_post_meta( $post_id, '_user_liked', true );
$liked_by = array();

	foreach($get_who_is_liking as $we_like_this) {
		$i_like_this = get_userdata($we_like_this);
	    $liked_by[] = $i_like_this->user_login;
	}

$liked_by_us = implode(', ', $liked_by);
```
And now the question would be: How do I update this with the ajax? :D

**Comment by JonMasterson** [comment]
Hello,
Glad you got it figured out. As for updating with ajax, that will require a bit more work. I touch [on it here](https://github.com/JonMasterson/WordPress-Post-Like-System/issues/8#issuecomment-69639147). I am working on a significant update to this system that will offer ajax widgets for functions 7-11 (and a few new ones, including what you have here). Widget lists for liked posts will respond without a screen refresh. I am also adding time data to each "like" — making it possible to properly display all liked posts from a certain time period. I currently offer functions to do this, but they return posts based on post date instead of the date the post was liked. I'm going to update the Read Me with this information. Hope this helps.
